### ISSUE TITLE
Fix summary items image sizes

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront#181]
https://community.e-com.plus/t/css-imagem-do-produto-no-checkout/182

**Purposed solution**

```scss
.ec-summary__item img {
  width: 50px;
}
```

_Backport to v1_
